name: aur-sync-light

on:
  #schedule:
  #  - cron: '0 8 * * *' 
  workflow_dispatch:
    inputs:
      push_dry_run:
        description: 'Perform a dry run of the push to AUR (true/false)'
        required: false
        default: 'true'
    
jobs:
  aur-sync:
    runs-on: ubuntu-latest

    env:
      AUR_ED25519_GITHUB: ${{ secrets.AUR_ED25519_GITHUB }}
      GIT_NAME: ${{ secrets.GIT_NAME }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      # TODO replace with info from repo.yml
      PKGS: grok-build-git grok-build-bin
      PUSH_DRY_RUN: ${{ github.event.inputs.push_dry_run || 'true' }}

    steps:
      - name: Check environment variables
        run: |
          if [[ -z "$AUR_ED25519_GITHUB" ]]; then
            echo "ERROR: AUR_ED25519_GITHUB is not set. Please set it in the repository secrets."
            exit 1
          fi

          if [[ -z "$GIT_NAME" || -z "$GIT_EMAIL" ]]; then
            echo "ERROR: GIT_NAME or GIT_EMAIL is not set. Please set them in the repository secrets."
            exit 1
          fi

          if [[ -z "$PKGS" ]]; then
            echo "ERROR: PKGS is not set. Please set it in the workflow environment variables."
            ecxit 1
          fi
      - name: Store helper lib
        run: |
          cat > lib.sh <<-'EOF'
            wf_get_pkgbuild_value() {
              local pkgbuild_file=$1
              local field=$2
              local value
              value=$(awk -v field="$field" '
                $0 ~ "^[[:space:]]*"field"=" {
                  sub(/^[[:space:]]*'"$field"'=[[:space:]]*/, "")
                  sub(/[[:space:]]*#.*$/, "")
                  gsub(/^["'\'']+|["'\'']+$/, "")
                  print
                  exit
                }
              ' "$pkgbuild_file")
              echo "$value"
            }

            wf_get_pkgbuild_version() {
              local pkgbuild_file=$1
              local pkgver=$(wf_get_pkgbuild_value "$pkgbuild_file" "pkgver")
              local pkgrel=$(wf_get_pkgbuild_value "$pkgbuild_file" "pkgrel")
              echo "$pkgver-$pkgrel"
            }

            wf_print() {
              local msg=$1
              echo "ℹ️  $msg"
            }

            wf_error() {
              local msg=$1
              echo "❌  $msg"
            }

            wf_version_gt() {
              local ver1=$1
              local ver2=$2
              local pkg=$3

              # normalize version if -git pkg. commit hash will be removed for comparison
              if [[ "$pkg" == *-git ]]; then
                norm() {   
                  # remove ecommit hash, not compatible with dpkg
                  # starting with, witthing upstream tag seems to work despite warning
                  # # TODO keep an eye on this version comparison
                  echo "$1" | sed -E 's/\.[0-9a-f]{7,}//'; 
                }
                ver1=$(norm "$ver1")
                ver2=$(norm "$ver2")
              fi

              # TODO suppress stdout to hide warning, if comparison never fails
              dpkg --compare-versions "$ver1" gt "$ver2" && return 0 || return 1
            }
          EOF

      - name: Prepare runner
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync tree

      - name: Setup AUR SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$AUR_ED25519_GITHUB" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          cat > ~/.ssh/config << EOF
            Host aur.archlinux.org
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
              User aur
          EOF

          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Clone AUR repositories
        run: |
          . lib.sh

          wf_print " => Packages to clone: $pkgs"

          pkgs=${PKGS:-}
          for pkg in $pkgs; do
            pkg_dir="aur/$pkg"
            url="ssh://aur@aur.archlinux.org/$pkg.git"

            mkdir -p "$pkg_dir"

            wf_print " ===> Cloning $url into $pkg_dir"
            git clone $url "$pkg_dir" || {
              wf_error " ===> Failed to clone $url into $pkg_dir"
              exit 1
            }
          done

      - name: Checkout github repo
        uses: actions/checkout@v3
        with:
          path: repo/

      - name: Dump tree
        run: |
          echo "Dumping directory tree for debugging:"
          tree -a -L 3 -I '.git'      

      - name: Sync AUR
        run: |
          . lib.sh

          pkgs=${PKGS:-}

          wf_print "Packages to update: $pkgs"
          for pkg in $pkgs; do
            wf_print " => Working on package: $pkg"

            monorepo_dir="repo"
            aurrepo_dir="aur/$pkg"
            
            src_dir="$monorepo_dir/$pkg"
            dest_dir="$aurrepo_dir"
 
            wf_print " ===> Force copying files from $src_dir to $dest_dir"
            # TODO: remove forced copy after sync logic is verified. -avIW => -avc
            rsync -avIW --delete --progress --exclude '.git' "$src_dir/." "$dest_dir/"

            # double check that all files were copied correctly
            changes=$(diff -rq --exclude=.git "$src_dir/." "$dest_dir/")
            if [[ -n "$changes" ]]; then
              wf_error " ===> Not all files copied correctly."
            fi
            wf_print " ===> All files copied correctly."

            wf_print " ===> Git adding changes in $dest_dir"
            git -C "$aurrepo_dir" add -A
            git -C "$aurrepo_dir" status

            # go further only index differs from HEAD
            if git -C "$aurrepo_dir" diff --cached --quiet; then
              wf_print " ===> No changes to commit for package $pkg."
              continue
            fi
            
            git config --global user.name "$GIT_NAME"
            git config --global user.email "$GIT_EMAIL"
            hash=$(git -C "$monorepo_dir" rev-parse HEAD)

            printf -v msg 'chore(sync): update %s from GitHub repo %s\n\nsource commit: %s' \
              "$pkg" "$GITHUB_REPOSITORY" "$hash"
            wf_print " ===> Committing changes with message:\n$msg"

            git -C "$aurrepo_dir" commit -m "$msg"

            push_cmd=(git -C "$aurrepo_dir" push)
            if [[ "$PUSH_DRY_RUN" == "true" ]]; then
              wf_print "Performing a dry run of the push."
              push_cmd+=(--dry-run)
            fi
            "${push_cmd[@]}"
          done

