name: aur-sync-light

on:
  #schedule:
  #  - cron: '0 8 * * *' 
  workflow_dispatch:
    inputs:
      push_dry_run:
        description: 'Perform a dry run of the push to AUR (true/false)'
        required: false
        default: 'true'
    
jobs:
  aur-sync:
    runs-on: ubuntu-latest

    env:
      AUR_ED25519_GITHUB: ${{ secrets.AUR_ED25519_GITHUB }}
      GIT_NAME: ${{ secrets.GIT_NAME }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      PKGS: grok-build-git grok-build-bin
      PUSH_DRY_RUN: ${{ github.event.inputs.push_dry_run || 'true' }}

      # internal 
      _PKGS_TO_UPDATE: ""

    steps:
      - name: Store helper lib
        run: |
          cat > lib.sh <<-'EOF'
            wf_get_pkgbuild_value() {
              local pkgbuild_file=$1
              local field=$2
              local value
              value=$(awk -v field="$field" '
                $0 ~ "^[[:space:]]*"field"=" {
                  sub(/^[[:space:]]*'"$field"'=[[:space:]]*/, "")
                  sub(/[[:space:]]*#.*$/, "")
                  gsub(/^["'\'']+|["'\'']+$/, "")
                  print
                  exit
                }
              ' "$pkgbuild_file")
              echo "$value"
            }

            wf_get_pkgbuild_version() {
              local pkgbuild_file=$1
              local pkgver=$(wf_get_pkgbuild_value "$pkgbuild_file" "pkgver")
              local pkgrel=$(wf_get_pkgbuild_value "$pkgbuild_file" "pkgrel")
              echo "$pkgver-$pkgrel"
            }

            wf_print() {
              local msg=$1
              echo "ℹ️  $msg"
            }

            wf_error() {
              local msg=$1
              echo "❌  $msg"
            }

            wf_version_gt() {
              local ver1=$1
              local ver2=$2
              local pkg=$3

              # normalize version if -git pkg. commit hash will be removed for comparison
              if [[ "$pkg" == *-git ]]; then
                norm() {   
                  # remove ecommit hash, not compatible with dpkg
                  # starting with, witthing upstream tag seems to work despite warning
                  # # TODO keep an eye on this version comparison
                  echo "$1" | sed -E 's/\.[0-9a-f]{7,}//'; 
                }
                ver1=$(norm "$ver1")
                ver2=$(norm "$ver2")
              fi

              dpkg --compare-versions "$ver1" gt "$ver2" && return 0 || return 1
            }
          EOF

      - name: Prepare runner
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Setup AUR SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$AUR_ED25519_GITHUB" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          cat > ~/.ssh/config << EOF
            Host aur.archlinux.org
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
              User aur
          EOF

          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Clone AUR repositories
        run: |
          . lib.sh

          pkgs=${PKGS:-}

          for pkg in $pkgs; do
            wf_print "==============================="
            wf_print "Cloning $url into $dest"

            url="ssh://aur@aur.archlinux.org/$pkg.git"
            dest="aur/$pkg"

            mkdir -p "aur/$pkg"

            git clone $url $dest
          done
          wf_print "==============================="

      - name: Checkout github repo
        uses: actions/checkout@v3
        with:
          path: repo/

      - name: Check data
        run: |
          _PKGS_TO_UPDATE=""
          pkgs=${PKGS:-}

          . lib.sh

          for pkg in $pkgs; do
            wf_print "==============================="
            wf_print "Checking package: $pkg"

            aur_pkbuild_file="aur/$pkg/PKGBUILD"
            repo_pkbuild_file="repo/$pkg/PKGBUILD"

            if [[ ! -f "$aur_pkbuild_file" ]]; then
              wf_print "Error: PKGBUILD not found in the checked-out AUR repository for package $pkg. Exiting."
              exit 1
            fi

            if [[ ! -f "$repo_pkbuild_file" ]]; then
              wf_print "Error: PKGBUILD not found in the checked-out GitHub repository for package $pkg. Exiting."
              exit 1
            fi

            repo_version=$(wf_get_pkgbuild_version $repo_pkbuild_file)
            aur_version=$(wf_get_pkgbuild_version $aur_pkbuild_file)

            wf_print "Repository version: $repo_version"
            wf_print "AUR version: $aur_version"

            if wf_version_gt "$repo_version" "$aur_version" "$pkg"; then
              wf_print "Repository version is newer than AUR version. Update needed."
              _PKGS_TO_UPDATE="$_PKGS_TO_UPDATE $pkg"
            else
              wf_print "No update needed for package $pkg."
            fi

          done
          wf_print "==============================="

          echo "_PKGS_TO_UPDATE=$_PKGS_TO_UPDATE" >> $GITHUB_ENV

          if [[ -n "$_PKGS_TO_UPDATE" ]]; then
            wf_print "Updates are needed for the following packages: $_PKGS_TO_UPDATE"
          else
            wf_print "No updates are needed for any packages."
          fi

      - name: Sync AUR
        if: env._PKGS_TO_UPDATE != ''
        run: |
          # TODO subtree

          . lib.sh

          pkgs=${_PKGS_TO_UPDATE:-}
        
          for pkg in $pkgs; do
            wf_print "==============================="
            wf_print "Syncing package: $pkg"
 
            rsync -av --exclude '.git' "repo/$pkg/." "aur/$pkg/"

            diff_out=$(git -C "aur/$pkg" diff)
            if [[ -n "$diff_out" ]]; then
              
              version=$(wf_get_pkgbuild_version "repo/$pkg/PKGBUILD")
              gh_repo="$GITHUB_REPOSITORY"
              msg="update to $version by automated sync from github ($gh_repo)"

              wf_print "Changes detected. Committing and pushing to AUR for package $pkg with version $version."
              wf_print "Commit message: $msg"

              git config --global user.name "$GIT_NAME"
              git config --global user.email "$GIT_EMAIL"

              git -C "aur/$pkg" add .
              git -C "aur/$pkg" commit -m "$msg"

              push_args=""
              if [[ "$PUSH_DRY_RUN" == "true" ]]; then
                wf_print "Performing a dry run of the push."
                push_args="--dry-run"
              fi
              git -C "aur/$pkg" push $push_args
            else
              wf_print "No changes detected. Nothing to commit."
            fi
          done
          wf_print "==============================="

