name: sync-aur

on:
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I am a skeleton workflow to make this workflow visible in the Actions tab so it can be run on the working branch."